---
driver:
  name: docker
  #socket: tcp://127.0.0.1:2376
  hostname: git.ci.local
  use_sudo: true

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  require_chef: false
  #init_environment: |
  #  # apt pkg required
  #  SALT_ROOT=${SALT_ROOT:-/tmp/kitchen/srv/salt}
  #  mkdir -p $SALT_ROOT;
  #  ln -fs /usr/share/salt-formulas/env/* $SALT_ROOT/
  #  # reclass required
  #  #mkdir -p $SALT_ROOT/reclass/classes
  #  #ln -fs /usr/share/salt-formulas/reclass/* $SALT_ROOT/reclass/
  #  #find $SALT_ROOT/git -name metadata -type d | xargs -I'{}' \
  #  #  cp -fa {}/service $SALT_ROOT/reclass/classes/
  vendor_repo:
    - type: apt
      url: http://apt.tcpcloud.eu/nightly
      key_url: http://apt.tcpcloud.eu/public.gpg
      components: main tcp-salt
  dependencies:
    - name: linux
      repo: apt
      package: salt-formula-linux
    # Test of git external dependencies that are not directly required
    - name: nginx
      repo: git
      source: https://github.com/tcpcloud/salt-formula-nginx.git
    - name: postfix
      repo: git
      source: https://github.com/tcpcloud/salt-formula-postfix
    #- name: salt
      #repo: apt
      #package: salt-formula-salt
  log_level: error
  formula: git
  grains:
    noservices: True
  state_top:
    base:
      "*":
        - git
  pillars:
    top.sls:
      base:
        "*":
          - git
verifier:
  name: inspec
  sudo: true


platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: centos-7.1


suites:

  - name: client_single
    provisioner:
      pillars-from-files:
        git.sls: tests/pillar/client_single.sls


# vim: ft=yaml sw=2 ts=2 sts=2 tw=125
